apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-webhook-url

# kubectl -n flux-system create secret generic discord-webhook-url \
# --from-literal=address=https://discord.com/api/webhooks/YOUR/WEBHOOK/URL

# Decode or Edit Secret:
# https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#decoding-secret