apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi
  namespace: synology-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
  fsType: 'ext4'
  dsm: "192.168.1.249"
  location: "/volume1"
  protocol: iscsi
reclaimPolicy: Delete
allowVolumeExpansion: true