# .sops.yaml
# This file tells SOPS which keys to use for encryption

creation_rules:
  # Rule for the 'infrastructure/talosconfig.yaml' file
  - path_regex: infrastructure/talosconfig(\.encrypted)?.yaml$
    age: age14652kzh6k85uzhll84excakw5pwtrcku88z2jw0tt6c9rp5wcdqq9aeyt0
    encrypted_regex: '^(ca|crt|key)$'

  # Rule for the 'infrastructure/kubeconfig.yaml' file
  - path_regex: infrastructure/kubeconfig(\.encrypted)?.yaml$
    age: age14652kzh6k85uzhll84excakw5pwtrcku88z2jw0tt6c9rp5wcdqq9aeyt0
    encrypted_regex: '^(certificate-authority-data|client-certificate-data|client-key-data)$'

  - path_regex: infrastructure/sealed-secrets-key(\.encrypted)?.yaml$
    age: age14652kzh6k85uzhll84excakw5pwtrcku88z2jw0tt6c9rp5wcdqq9aeyt0

  - path_regex: \.tfvars$
    age: age14652kzh6k85uzhll84excakw5pwtrcku88z2jw0tt6c9rp5wcdqq9aeyt0

  - path_regex: \.tfstate$
    age: age14652kzh6k85uzhll84excakw5pwtrcku88z2jw0tt6c9rp5wcdqq9aeyt0