apiVersion: v1
kind: Namespace
metadata:
  name: synology-csi
  # Error: kubectl get events -n synology-csi
  # create Pod synology-csi-controller-0 in StatefulSet synology-csi-controller failed error: pods "synology-csi-controller-0" is forbidden: violates PodSecurity "baseline:latest": non-default capabilities (containers "csi-provisioner", "csi-attacher", "csi-resizer", "csi-plugin" must not include "SYS_ADMIN" in securityContext.capabilities.add), host namespaces (hostNetwork=true), privileged (containers "csi-provisioner", "csi-attacher", "csi-resizer", "csi-plugin" must not set securityContext.privileged=true)
  labels:
    pod-security.kubernetes.io/enforce: privileged