---
clusterName: homelab
talosVersion: v1.12.1
endpoint: https://192.168.3.1:6443
allowSchedulingOnMasters: true
allowSchedulingOnControlPlanes: true
nodes:
  - hostname: node1
    ipAddress: 192.168.3.1
    installDisk: /dev/nvme0n1
    controlPlane: true
  # - hostname: node2
  #   ipAddress: 192.168.3.2
  #   installDisk: /dev/sda
  #   controlPlane: true
  # - hostname: node3
  #   ipAddress: 192.168.3.3
  #   installDisk: /dev/sda
  #   controlPlane: true