---
# Example: https://github.com/budimanjojo/talhelper/blob/master/example/talconfig.yaml
clusterName: homelab

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.3.1:6443
allowSchedulingOnControlPlanes: true

nodes:
  - hostname: node1
    ipAddress: 192.168.3.1
    installDisk: /dev/nvme0n1
    controlPlane: true

  # - hostname: node2
  #   ipAddress: 192.168.3.2
  #   installDisk: /dev/nvme0n1
  #   controlPlane: true

  # - hostname: node3
  #   ipAddress: 192.168.3.3
  #   installDisk: /dev/sda
  #   controlPlane: true

# Controller patches
controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
  patches:
    - "@./patches/controller/cilium-prep-patch.yaml"