# deployment + service for MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: demo-webapp
  labels:
    app: mongo
spec:
  replicas: 1 # scale database using statefulset not deployment
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.6
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: demo-webapp
spec:
  selector:
    app: mongo # match labels of pods in deployment
  ports:
  - port: 27017 # any service port
    targetPort: 27017 # forward to container port
