context: talos-cluster
contexts:
    talos-cluster:
        endpoints:
            - 10.123.20.201
            - 10.123.20.202
            - 10.123.20.203
            - 10.123.20.204
        nodes:
            - 10.123.20.201
            - 10.123.20.202
            - 10.123.20.203
            - 10.123.20.204
        ca: ENC[AES256_GCM,data:TOcO4u9+88PTe5TWC4VTeMMfCBpX9poy+6h52WlXXP9D/FmhRWm+z8j93qHeIIXHGummr9in4x34QsHOgLGa5jyLcXnRiiqatcDwijsOft1/yu500OUfUF80DDbHjD4hBNpcj8roieHj0FDDl0EfTXV7uZmtVWzWsNeHTd1iZlTDIH/MMYpu/Fw8Xm+EkJTV/soV50lGnuEVeSwrwsq+5Z9fHhdjDH98pMLwpVyXSmmeSre+GPDPeP2GtoaPU93cKsOdJRh12J6GhV5dg+NYfz2q5GuGhHt5g7t4Q8syGl1nPhR/XX7gE480Z4ZwHY/FhoW9RmuUCMPQB9JawbyJiAiAGo3w2DmOO/BD7qVxrKtNWBQn1tZRmwYwmq+k0Gfq/glfSqxMFsIWLTzyXPfkZ3sEWdgqaliup443jBlO5kFlCs0sQqqYSO7xaawLShHV3Ixp366DrAqK6JFXBTP/oxn0ds8qmZJNMhyuM7w6tkRmUarH07dEaeBajECuoVHH+mPJgeKPewsWBiC7VhIXhLt0eR9HlB4lmU2ao6Oa0fM/w3yjlLsZjVD38lTyzIF1JvgdQkphP0zi9xXOJPtYGZMYK/yAZrMAak5RiVBFOlcFT8qafQMfq2DnhOBlytazATky8u/wRiUhjAsPGLyjl9mqom5wqtO5DGVJM4+0OacNgiK6OCh3uwhnkZV/Yy0J6GW3ppk2C2K+esDI2SvBJTSfGFm+gUDOhe1blX/YT/f8pGwMkRIXObDh0tIpnPUJcKdUUMI0/QR1fRYa8px4/14N4hcbQmWfqaAdVIZuArBv9/1BGn4K5i/5uingj0TyGtFcFV7KyHcBcBy0ke2BoKm/oU0PhDG8HLxF4Y1x5qOqfx+s,iv:IKb2i+ZBh/6Hh08YToyXldiwD50xccjEkqZHVotHhM8=,tag:Drq0TOoJ6scx71a/BqiiZg==,type:str]
        crt: ENC[AES256_GCM,data:MJ9mHzXlItIlHDcYyeUodvodQ78c6+TAxVWUhqtPFZR9AOTLNvKJGfn00vVM7FXW0dhiB54452CoPmxvFKCivPhcoJbMxsnJwchPRXwuN/vxPBn1cVg+z1Xecmn+y8tP9lOjkyWGxNHCHdihztKpybkOo7vRG97Jpgem8I5MX5j/cUmOy7QaxMHIhS739FhA8ymkA+bN3YX9fjQ33JECKZk1eN1mTF3KJGbpRJTBkDo5BDwOhso2FcwmlnrNfNkHYJgkoNTWOZgK1THKWWqxF7UTpm/LOHA6Mog0RyQM5T0J76QdQXGnMa+b2am4tOu3FLJ7sOxzycD12IJJDleBTzTupC8MCDrA3fjXNOlcYCmABEzf0k/dWpMyMiWf7kOpx9jvnnCQktEy59wQjsP6CtFfzOo16/F08MgVKK3icElPIy1EUc1PH6XstT1XuaCoxzR8xCNq7NaFuxDfLnAebug0g7DcVWuIBCtgC6a8AJO5kltGsc5HGt4VwF9bFdxFts1tEbWIFS/bzYjenFLnkOtZahUknpVGSi0ogjW5TfVRUgPD41xz/ceG4nTgyD/1ASp5a6Y2s7YNfxfzSSf4pmVK2Ncu9cYuFB+xF2loRi40C2wDPQ5CzhEx+bcvsOg86VpDir14uUy9fMiUd6szwMIXlZBW8Cs45Wk0FY5zZnP8nFqK+NLHLENYzT8fL/Dc3GvHRZX4sBezpaM1izgP+22up/fGRxdLX7RtSQ8OQpaOvqjwsCfG2fH/Q1u6yaBiPV9gyV4TTWvQa/gMOW8FM/ZRhB0R5s7oTfkkkqCVmwoChPMGm1w6Mw==,iv:WMlnuWmUrkrkG7AtYGrHNDJfIe50wX1dPZ0L+kk35wc=,tag:JRn+yP+td/IaGXojCLsDDQ==,type:str]
        key: ENC[AES256_GCM,data:YMep2y7qzDkxqj16pq+uRWNq/n7oRL+wIrNZ7JCeQ5Jr/X2mm7l3Rxvlfl4yI3bkPXBoUlU/DDCDjBzXYEL9MM4X+b4hD8elPTQ+hN/XBtpteJeMO3RDjS4otbcB+bAq05pvav7CdOi4jtnV248s7cMSdhr7Qbl+TTn0dimW9ceFf+PBHufUGCh4YhnhpUNYfrC2X29wBWFjnGVR+eLaO3l3zkrJFi82G5oAdMLo7EHmojiN,iv:2TUOPnXFP5qIItefEfjcRfQ9GQ+p40GHzw7vnecWYm8=,tag:kJcSq5BE3ClTPbhYHHUmzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVkdZQk02M0k0cmRETmRw
            K1RyZTdPSVJxeTg2MzZLeWZHZkJ2UUljS1NBClVtWHRsdUtYNWRlK0JMNkpSR2tC
            aHcwS1hiVG1xNkRnSzU0dDBCTW5JRTgKLS0tIDREVXJiSVRTRUtRam5iRElKZW5R
            dlJMNjg0ZEh5MlhhM2tBOFhqL1UzVEUK0t2LUYuIKRjL5f4Mb22Nt5fWVGuzXEqH
            IaNan6znIFfNNMa5z4TGcg+m1pfVh3eUM8GU0a5V0kedJixX1kwmAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14652kzh6k85uzhll84excakw5pwtrcku88z2jw0tt6c9rp5wcdqq9aeyt0
    encrypted_regex: ^(ca|crt|key)$
    lastmodified: "2026-06-22T01:46:55Z"
    mac: ENC[AES256_GCM,data:WF1rvwPK1dtvf/LBt+Kc/nTl3l8RRAcNiNWJuFNGj8FG/S+b/FsnjfwzK0Eki6d45kssNckZAhs6IQ+rRhOv6AGqLNCj9K06Czl3d6quV2PvZ35lBeeq5Vj3zNxDSeLL1im8d3gn8DxF2FwpVoxJ91Drcioz5B0IkSNNI1mqPvk=,iv:4niiggya/dW1Udb8DxCoc1TJjG1bCD/bU7nlDYsZXKQ=,tag:ahGB8NrpJT0gO6IJiJ9ArA==,type:str]
    version: 3.13.1
