apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    url: ENC[AES256_GCM,data:VkRtHMkgIMxZXlUlujQgoOOYLMQotfHcJBDakODEbOJEMFMnP9G+3XbXJdF0zjlAsO7GGowrEZZYOFvhGUAIzeaxngjyEL8me6Gs9yR03Go1l7MPHfm0B3mO+FwIwPUnib2KzhXcsYmZrM0tYpV9+7+q3vH8OdhEZg==,iv:C/IHwiAbwUkLbwFxDkgJj3PDJNuy4Ys/tt+8ThYJAhw=,tag:MIdUVUvnYRPaeSF1PvXsUw==,type:str]
sops:
    age:
        - recipient: age14652kzh6k85uzhll84excakw5pwtrcku88z2jw0tt6c9rp5wcdqq9aeyt0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOEtNT2RsZVN6Z2JvM3dR
            VTJOZ3lNbjBDM0ZjVnFQU1VWZG9Zd1M0Z0EwCnlxeWJKNmZKalVuSzcvQWlWTnM0
            bVdMdU8vMHJpRHJyZC82V2w0MTh5dUEKLS0tIDRabm1zT1R0RGFuR2t3eEhQaGVB
            QzFOY2d3ZWxtQWtrQjlRVDkrOXhVZ2sK/oT7upBfqTPJcxzifJFMUZ0aweHhh8p3
            Zr8SxTtkSo/kzmN64ckhU5cXPmMKAUKOAzIvT2IcoSfNAzymxflsrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T02:43:53Z"
    mac: ENC[AES256_GCM,data:t6a/M7uHEO3HQZMC8UCVQrxpG6SgLCPImaFyuXUYr+aGkGuPmd4INd+X0a39VwFu1N4o91lyjrOCBmsaacNF0YyXU1N2He8iTpXiaz33ZLL7WMghpXpCq40yollY2ao6cN/QgJu3aO308V/LUFFho4HEtL4ZR/g5QOn+PmdkQvk=,iv:gX0xUya0cuPPYAKXPXTvNsNf3svLz7ZCJF3CvUuR7K4=,tag:KjDpirjwF+X10Tlq6ZlfYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
