apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:6+g3O11px4IoWAfepzoy21Hps+bWJvquizBbx6JkEjsKG3ShxZZh6P7gQxFg2rhHOmEBwYNwnG9Mq4MG7itrG1M23jG7NZ3Qh/IyG/Bh52NULBOFzCcXbEIPxQuo6rwzLhk2vTjATZ0xTQotvY0UWRgDR76RVVgF5g==,iv:SpNajVJCH+/bydgeLTjJvhbGpEVXT1J5xmCAfz2VX7Q=,tag:VFYpC3s0AThNInb8Tr1IOg==,type:str]
sops:
    age:
        - recipient: age14652kzh6k85uzhll84excakw5pwtrcku88z2jw0tt6c9rp5wcdqq9aeyt0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOEtNT2RsZVN6Z2JvM3dR
            VTJOZ3lNbjBDM0ZjVnFQU1VWZG9Zd1M0Z0EwCnlxeWJKNmZKalVuSzcvQWlWTnM0
            bVdMdU8vMHJpRHJyZC82V2w0MTh5dUEKLS0tIDRabm1zT1R0RGFuR2t3eEhQaGVB
            QzFOY2d3ZWxtQWtrQjlRVDkrOXhVZ2sK/oT7upBfqTPJcxzifJFMUZ0aweHhh8p3
            Zr8SxTtkSo/kzmN64ckhU5cXPmMKAUKOAzIvT2IcoSfNAzymxflsrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T02:47:08Z"
    mac: ENC[AES256_GCM,data:NbzlqHHbwtZWCVr+z8fVqYDlaJfBX09CzCvyFGEkqll5UwqPfUEppDBVP+3AOcRQYWQovpwdGCJEfU1yMfRBogSAX8a+cyLwiS6KQuglA+IjTc8NL/yIPyPrdksmIWZF33J3ITIUstGgP5TxlsG9tjmMY9snVVXfBegEp2k54xc=,iv:7c+u+jOqaSwJKicFqnRfSahbaO0nZYL7XkCVCATxtSE=,tag:Fx8sKzQaFw1AmvEvkKgEnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
