apiVersion: ENC[AES256_GCM,data:lcA=,iv:AKPHV1E3F8G9nY6Cam8v5H0bW+jLDZ6iySCAydII1bk=,tag:AEGOVskbhgpc+G/c/7iIKA==,type:str]
kind: ENC[AES256_GCM,data:sU1q8S9y,iv:gXTjuKCUzKAFlVRAUwrsorpQyJNMqMigDDUTenu7v5w=,tag:uwy0CYEh3TVodRagtO0Ceg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ivof0XFJ54nw9yzNUy5JXajWrg==,iv:g3l3iws4TaNKS7zwOLIeugJAgXmIUZb2+zdclZXzxl8=,tag:fMLn4Pb2jPBsWEXKqmKYkQ==,type:str]
    namespace: ENC[AES256_GCM,data:jKLR7Mhr1k3HYOY=,iv:PN0okndc90YBlU/d8DsFa6EThHLWQa6RSMXUju5QlfM=,tag:g0j3ZaUpgKkpMXQCrr3nOA==,type:str]
stringData:
    url: ENC[AES256_GCM,data:reuJqCelS349sDjyZ7WxlqJ4VOg9BTgQm8Z4e3E4BKvI13XPbqQu+mhDoVW8sf3WMhe9IqLhPyDv2JrLKHB4s9FqOcl0ChgbDUwno68LVgQ1XH02F2MqmfrCHj9F58Jgj+hVNonbozUtxHl3UXqfr9Cm2jtLtQtHTA==,iv:46UJfTgSCBQ0BQI8kpqEI9MJ8M+uHQaoJDC7uKegSNc=,tag:Vp4MEQ2ptBlQtOEAG5rg1A==,type:str]
sops:
    age:
        - recipient: age14652kzh6k85uzhll84excakw5pwtrcku88z2jw0tt6c9rp5wcdqq9aeyt0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSHB2RzAwYlBmaUNEOFFk
            YStTb25EazF0Mm10M2VlYUp2T3dUWFNUOFdZCnFXS2ZPdS9QS3ZaZjhTclUvU3oz
            ZGNCSVVITWhXOCtCSlUwT05VUlN4SzgKLS0tIFcyVFhPQW9DNll2amFPMk9ubVhn
            K2FvSWwyV3JZTlhqWE4waktNZ1R1ZHcKBI6nCFJsSnuzkNEF+9UhclJYioVUCPgE
            dwmZmI4wesGe2jTZwggZxpI913z3jpCVCzbeYiKo+KnWSVcPFW7rMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T02:34:15Z"
    mac: ENC[AES256_GCM,data:EvKZUrNNzQpeW6gHReyk9XQw2ZBbmxXIlH6OYmBgLDM4D+1NktUmIVgD6V2nmL+hi1thbskE6qpz3SbhWnB3zqHe9rKULKBOdJGZ5VUeFOyVBd0eahgMAJsXnxJq+PyagoTG7J+DR3UqAlD/0Y+XktzstZXDpzlR7KMLYvj7tAQ=,iv:iuxWpthY4j3DhKd3LMkEVpW19aqusr9z7IMb6Iwcel4=,tag:mY8DEQPDP5oJvZ9oslfmyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
