apiVersion: v1
kind: Secret
metadata:
    name: ghcr-login-secret
    namespace: synology-csi
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:dlOx1ii0O9cwJ99Lghhe4DrHFce8Vedpv7x6ccIdC0eM6nHNAkNyrHBw4ITwTvWEf6c98VGHF1wwishJZL5noGpoIv/cBKKKpCbZo8o5dSU5mz9P0YgfE7zMFnQpzs5Ta1sb2c8+2tT5b6DTj9+oWQ2Q6VnXTr+FZx8BXWzSZ3MJdmsoyvxxJ4PLb8QoPIY5E3X2TVSteeq0Bx1xO09jo9/RnJ44j9xeJO8q2WLZuRaeVqmzQmty88ct+2yeGwECsWSG7YodaeDiZCuc9PCAV/qVwNrq0SRa4QtgqojyYGnBGq/U1ImU6NoAuVwbl6/p,iv:pgO2p/c20uK2f7hq0SH4r62/MTK7VENdGYOe4KkHPzw=,tag:LUQkeVFHq87GXCKJYCp3HQ==,type:str]
sops:
    age:
        - recipient: age14652kzh6k85uzhll84excakw5pwtrcku88z2jw0tt6c9rp5wcdqq9aeyt0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYmhPZHpraGlMUWphMFpt
            K3NOcWQ0NmtybXRuNCtTdlZFTFZQbVBYMVJJCkdoMFlYTUVpTk9nNk8xOTR4aTVU
            ZmVYczcyNEdmc1RWTzVPZ2J2aXVkamsKLS0tIEhIS0tNeXF2dlRsVnNKckR3Z3lp
            THdSa2NXcVZoUTNzTWhxcTF2OTVTcEEKgYiHlzPP2OGRzeWfEI/RXvmkUGBMG09o
            1wxDj7U1KwbsDEjhb4h/xaWyi7T5InBWnVRaYpp3Ho9n9ZeUHUMS/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T23:00:14Z"
    mac: ENC[AES256_GCM,data:yF6D3uARpDlgz/70NZ1jT5aq9B04gCKc6O14J1ezskMPJQrwMX7eRaojYluHYN5SN+wmsQWb6FpvIlZfEkRPNC0X9nU1iYvslmLAdq4j1QfA6slHeGKHOmJQKw27x8PTW+vn9ZJCvnbIF05ZKDhZk6bsL5aStdpe+LGJLdKqolY=,iv:zKusgH4OiSMAj/+QpvIZmSq7lwyjf4RlreTOH4XVrwE=,tag:pbtA6IS1ycHdEqzymq+Nmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
